# Generated by Django 2.1.1 on 2019-01-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdo_number', models.DecimalField(decimal_places=0, max_digits=9)),
                ('company', models.CharField(max_length=128)),
                ('nip', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_duration', models.DateField()),
                ('payment_deadline', models.SmallIntegerField()),
                ('offer_deadline', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('segment', models.CharField(choices=[('1', 'AUTOMOTIVE, TRANSPORT & AERONAUTIC'), ('2', 'CHEMICAL & PHARMACEUTICAL'), ('3', 'CONSTRUCTION, DECONSTRUCTION & MATERIALS '), ('4', 'ELECTRONIC AND ELECTRIC PRODUCTS'), ('5', 'ENVIRONMENTAL SERVICES'), ('6', 'FOOD AND BEVERAGE'), ('7', 'HEALTHCARE AND SOCIAL WORK ACTIVITIES'), ('8', 'MINING & QUARRYING'), ('9', 'OIL & GAS'), ('10', 'OTHER MANUFACTURING'), ('11', 'PRIVATE SERVICES'), ('12', 'PULP & PAPER'), ('13', 'TRANSPORTATION & STORAGE'), ('14', 'WHOLESALE, RETAIL TRADE')], max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postal', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=128)),
                ('bdo_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculation_app.Bdo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_transport_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('instalation_transport_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('management_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('logistic_details', models.CharField(max_length=256)),
                ('quality_details', models.CharField(max_length=256)),
                ('waste_mass', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costs_mg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('margin_mg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation_app.Calculation')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('postal', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=128)),
                ('bdo_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculation_app.Bdo')),
            ],
        ),
        migrations.CreateModel(
            name='WasteCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='subcontractors',
            name='waste_code',
            field=models.ManyToManyField(to='calculation_app.WasteCodes'),
        ),
        migrations.AddField(
            model_name='order',
            name='subcontractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation_app.Subcontractors'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='subcontractor',
            field=models.ManyToManyField(through='calculation_app.Order', to='calculation_app.Subcontractors'),
        ),
    ]
