# Generated by Django 2.1.1 on 2019-01-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calculation_app.Clients'),
            preserve_default=False,
        ),
    ]
