# Generated by Django 2.1.5 on 2019-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='containter',
            field=models.CharField(choices=[('1', '240l bin'), ('2', '1100l bin'), ('3', 'Container 7m'), ('4', 'Container 20m'), ('5', 'Container 34m'), ('6', 'Barrel'), ('7', '1000l DPPL'), ('8', 'EURO-Pallets')], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=32, verbose_name=(('1', 'PLN/Mg'), ('2', 'PLN/kurs'), ('3', 'PLN/pojemnik'))),
        ),
    ]
