# Generated by Django 2.1.5 on 2019-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_app', '0002_calculation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='bdo_number',
        ),
        migrations.RemoveField(
            model_name='subcontractors',
            name='bdo_number',
        ),
        migrations.AddField(
            model_name='clients',
            name='nip',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcontractors',
            name='nip',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bdo',
        ),
    ]
