# Generated by Django 2.1.5 on 2019-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_app', '0003_auto_20190126_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecodes',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
