# Generated by Django 2.1.5 on 2019-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_app', '0004_auto_20190126_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecodes',
            name='description',
            field=models.TextField(),
        ),
    ]
